// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbdktcdcsgydeihgzaqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iZGt0Y2Rjc2d5ZGVpaGd6YXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjY1ODYsImV4cCI6MjA1OTI0MjU4Nn0.GxZ7wrkCCpxKnoqTLZXNj9wFMb4bHLVQDDpoh3bD4Lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);